from src.element import Element

ROLE_ATTACKER = "Attacker"
ROLE_HEALER   = "Healer"
ROLE_TANKER   = "Tanker"

ROLE_COLOR = {
    ROLE_ATTACKER: (231,  76,  60),
    ROLE_HEALER:   ( 72, 199, 142),
    ROLE_TANKER:   ( 88, 166, 255),
}
ROLE_ICON = {
    ROLE_ATTACKER: "",
    ROLE_HEALER:   "",
    ROLE_TANKER:   "",
}

ALL_CHARS = [
    {
        "name": "Windah", "element": Element.FIRE,
        "role": ROLE_ATTACKER, "hp": 320, "attack": 80, "defense": 18,
        "image": "assets/characters/Windah_1.png",
        "basic": {"name": "Ember Strike",  "power": 0},
        "skill": {"name": "Inferno Blast", "power": 55, "type": "attack",
                  "cooldown": 3, "desc": "Ledakan api masif ke satu musuh"},
    },
    {
        "name": "SunFlower", "element": Element.FIRE,
        "role": ROLE_HEALER, "hp": 350, "attack": 45, "defense": 28,
        "image": "assets/characters/SunFlower.png",
        "basic": {"name": "Scorch Touch", "power": 0},
        "skill": {"name": "Solar Bloom",  "power": 90, "type": "heal",
                  "cooldown": 3, "desc": "Energi matahari pulihkan HP besar"},
    },
    {
        "name": "Ambatron", "element": Element.FIRE,
        "role": ROLE_TANKER, "hp": 560, "attack": 42, "defense": 68,
        "image": "assets/characters/ambatron.png",
        "basic": {"name": "Lava Bash",    "power": 0},
        "skill": {"name": "Magma Shield", "power": 45, "type": "attack",
                  "cooldown": 3, "desc": "Bentengan lava balik serang musuh"},
    },
    {
        "name": "IshowSpeed", "element": Element.WATER,
        "role": ROLE_ATTACKER, "hp": 310, "attack": 82, "defense": 16,
        "image": "assets/characters/IshowSpeed.png",
        "basic": {"name": "Tidal Slash",  "power": 0},
        "skill": {"name": "Ocean Surge",  "power": 58, "type": "attack",
                  "cooldown": 3, "desc": "Gelombang laut menghantam keras"},
    },
    {
        "name": "Tung Sahur", "element": Element.WATER,
        "role": ROLE_HEALER, "hp": 360, "attack": 40, "defense": 30,
        "image": "assets/characters/TungTungsahur.png",
        "basic": {"name": "Water Splash", "power": 0},
        "skill": {"name": "Tide Mend",    "power": 95, "type": "heal",
                  "cooldown": 3, "desc": "Aliran air dingin pulihkan HP besar"},
    },
    {
        "name": "Balmond", "element": Element.WATER,
        "role": ROLE_TANKER, "hp": 580, "attack": 38, "defense": 72,
        "image": "assets/characters/balmond.png",
        "basic": {"name": "Ice Punch",    "power": 0},
        "skill": {"name": "Glacier Slam", "power": 48, "type": "attack",
                  "cooldown": 3, "desc": "Lempar bongkahan es raksasa"},
    },
    {
        "name": "Bagasdribble", "element": Element.LIGHT,
        "role": ROLE_ATTACKER, "hp": 300, "attack": 84, "defense": 20,
        "image": "assets/characters/bagasdribble.png",
        "basic": {"name": "Vine Whip",    "power": 0},
        "skill": {"name": "Petal Storm",  "power": 60, "type": "attack",
                  "cooldown": 3, "desc": "Badai kelopak tajam menghujam musuh"},
    },
    {
        "name": "Keju joget", "element": Element.LIGHT,
        "role": ROLE_HEALER, "hp": 345, "attack": 42, "defense": 26,
        "image": "assets/characters/Keju joget_1.png",
        "basic": {"name": "Leaf Touch",   "power": 0},
        "skill": {"name": "Forest Bloom", "power": 92, "type": "heal",
                  "cooldown": 3, "desc": "Energi hutan pulihkan HP besar"},
    },
    {
        "name": "Masamba", "element": Element.DARK,
        "role": ROLE_TANKER, "hp": 555, "attack": 40, "defense": 70,
        "image": "assets/characters/masamba.png",
        "basic": {"name": "Bark Bash",    "power": 0},
        "skill": {"name": "Root Crush",   "power": 46, "type": "attack",
                  "cooldown": 3, "desc": "Akar raksasa meledak dari tanah"},
    },
    {
        "name": "Faiz immo", "element": Element.WIND,
        "role": ROLE_ATTACKER, "hp": 295, "attack": 88, "defense": 15,
        "image": "assets/characters/ayanokouji.png",
        "basic": {"name": "Gust Slash",   "power": 0},
        "skill": {"name": "Tornado Spin", "power": 62, "type": "attack",
                  "cooldown": 3, "desc": "Pusaran angin memotong semua arah"},
    },
    {
        "name": "Windi", "element": Element.WIND,
        "role": ROLE_HEALER, "hp": 340, "attack": 38, "defense": 27,
        "image": "assets/characters/Windi.png",
        "basic": {"name": "Breeze Touch", "power": 0},
        "skill": {"name": "Cyclone Heart","power": 90, "type": "heal",
                  "cooldown": 3, "desc": "Mata badai yang damai pulihkan HP"},
    },
    {
        "name": "Pakvincent", "element": Element.WIND,
        "role": ROLE_TANKER, "hp": 540, "attack": 44, "defense": 65,
        "image": "assets/characters/pakvincent.png",
        "basic": {"name": "Wind Wall",    "power": 0},
        "skill": {"name": "Whirlwind",    "power": 44, "type": "attack",
                  "cooldown": 3, "desc": "Angin puyuh menghantam musuh"},
    },
    {
        "name": "Kumar", "element": Element.EARTH,
        "role": ROLE_ATTACKER, "hp": 330, "attack": 78, "defense": 22,
        "image": "assets/characters/kumar.png",
        "basic": {"name": "Rock Throw",   "power": 0},
        "skill": {"name": "Earthquake",   "power": 56, "type": "attack",
                  "cooldown": 3, "desc": "Guncangan bumi meremukkan musuh"},
    },
    {
        "name": "Juki", "element": Element.EARTH,
        "role": ROLE_HEALER, "hp": 355, "attack": 40, "defense": 32,
        "image": "assets/characters/juki.png",
        "basic": {"name": "Stone Salve",  "power": 0},
        "skill": {"name": "Terra Surge",  "power": 88, "type": "heal",
                  "cooldown": 3, "desc": "Energi bumi pulihkan HP besar"},
    },
    {
        "name": "Mambo", "element": Element.EARTH,
        "role": ROLE_TANKER, "hp": 590, "attack": 36, "defense": 75,
        "image": "assets/characters/mambo.png",
        "basic": {"name": "Boulder Bash", "power": 0},
        "skill": {"name": "Landslide",    "power": 50, "type": "attack",
                  "cooldown": 3, "desc": "Longsor batu menghancurkan musuh"},
    },
    {
        "name": "HengkerwibuproTzy", "element": Element.DARK,
        "role": ROLE_ATTACKER, "hp": 300, "attack": 90, "defense": 14,
        "image": "assets/characters/squadhengker.png",
        "basic": {"name": "Spark Bite",   "power": 0},
        "skill": {"name": "Thunder Howl", "power": 64, "type": "attack",
                  "cooldown": 3, "desc": "Petir menyambar dengan dahsyat"},
    },
    {
        "name": "Masmasnunjuk", "element": Element.LIGHT,
        "role": ROLE_HEALER, "hp": 340, "attack": 42, "defense": 25,
        "image": "assets/characters/masmasnunjuk.png",
        "basic": {"name": "Jolt Mend",    "power": 0},
        "skill": {"name": "Arc Revival",  "power": 94, "type": "heal",
                  "cooldown": 3, "desc": "Listrik revitalisasi pulihkan HP besar"},
    },
    {
        "name": "Patrick", "element": Element.DARK,
        "role": ROLE_TANKER, "hp": 545, "attack": 46, "defense": 67,
        "image": "assets/characters/patrickplenger.png",
        "basic": {"name": "Charge Guard", "power": 0},
        "skill": {"name": "Static Crush", "power": 48, "type": "attack",
                  "cooldown": 3, "desc": "Ledakan statis menghantam musuh"},
    },
    {
        "name": "Mengerikan", "element": Element.DARK,
        "role": ROLE_ATTACKER, "hp": 10, "attack": 999, "defense": 999,
        "image": "assets/characters/mengerikan.png",
        "basic": {"name": "frightened", "power": 1},
        "skill": {"name": "void storm", "power": 1, "type": "attack",
                  "cooldown": 3, "desc": "Ledakan badai kehampaan yang menghantam musuh"},
    },
]


CHAR_BY_NAME = {c["name"]: c for c in ALL_CHARS}

STAGE_ENEMIES = {
    1: [  
        {"name": "Mengerikan",    "element": Element.FIRE,      "role": ROLE_ATTACKER,
         "hp": 250, "attack": 55, "defense": 12,
         "image": "assets/characters/mengerikan.png",
         "basic": {"name": "Claw Strike",   "power": 0},
         "skill": {"name": "Rage Burst",    "power": 40, "type": "attack", "cooldown": 3,
                   "desc": "Serangan wajah mengerikan"}},
        {"name": "Doraemon",      "element": Element.WATER,     "role": ROLE_HEALER,
         "hp": 280, "attack": 35, "defense": 20,
         "image": "assets/characters/doraemon.png",
         "basic": {"name": "Gadget Zap",    "power": 0},
         "skill": {"name": "Pocket Heal",   "power": 70, "type": "heal",   "cooldown": 3,
                   "desc": "Alat ajaib dari kantong pulihkan HP"}},
        {"name": "Kucinguiaeo",   "element": Element.WIND,    "role": ROLE_TANKER,
         "hp": 420, "attack": 30, "defense": 50,
         "image": "assets/characters/kucinguiaeo.png",
         "basic": {"name": "Paw Slam",      "power": 0},
         "skill": {"name": "Cat Barrier",   "power": 35, "type": "attack", "cooldown": 3,
                   "desc": "Serangan pertahanan kucing liar"}},
    ],
    2: [  
        {"name": "Serigalasumatra","element": Element.WIND,     "role": ROLE_ATTACKER,
         "hp": 290, "attack": 68, "defense": 16,
         "image": "assets/characters/serigalasumatra.png",
         "basic": {"name": "Fang Slash",    "power": 0},
         "skill": {"name": "Wolf Howl",     "power": 50, "type": "attack", "cooldown": 3,
                   "desc": "Lolongan serigala sumatra yang kuat"}},
        {"name": "Masmasnunjuk",  "element": Element.EARTH,     "role": ROLE_HEALER,
         "hp": 300, "attack": 40, "defense": 28,
         "image": "assets/characters/masmasnunjuk.png",
         "basic": {"name": "Point Strike",  "power": 0},
         "skill": {"name": "Earth Mend",    "power": 75, "type": "heal",   "cooldown": 3,
                   "desc": "Energi tanah pulihkan HP tim"}},
        {"name": "Rajakucing",    "element": Element.DARK, "role": ROLE_TANKER,
         "hp": 450, "attack": 36, "defense": 58,
         "image": "assets/characters/rajakucing.png",
         "basic": {"name": "Royal Slash",   "power": 0},
         "skill": {"name": "Thunder Reign", "power": 42, "type": "attack", "cooldown": 3,
                   "desc": "Raja kucing menyerang dengan petir"}},
    ],
    3: [  
        {"name": "Thomasalphaedisound","element": Element.FIRE, "role": ROLE_ATTACKER,
         "hp": 320, "attack": 75, "defense": 20,
         "image": "assets/characters/thomasalphaedisound.png",
         "basic": {"name": "Sound Blast",   "power": 0},
         "skill": {"name": "Infernal Note", "power": 55, "type": "attack", "cooldown": 3,
                   "desc": "Nada keras membakar musuh"}},
        {"name": "Doraemon",      "element": Element.WATER,     "role": ROLE_HEALER,
         "hp": 310, "attack": 42, "defense": 25,
         "image": "assets/characters/doraemon.png",
         "basic": {"name": "Gadget Wave",   "power": 0},
         "skill": {"name": "Deep Restore",  "power": 80, "type": "heal",   "cooldown": 3,
                   "desc": "Alat dari masa depan pulihkan HP"}},
        {"name": "Mambo",         "element": Element.EARTH,     "role": ROLE_TANKER,
         "hp": 500, "attack": 44, "defense": 65,
         "image": "assets/characters/mambo.png",
         "basic": {"name": "Heavy Stomp",   "power": 0},
         "skill": {"name": "Quake Crush",   "power": 48, "type": "attack", "cooldown": 3,
                   "desc": "Hentakan bumi yang menghancurkan"}},
    ],
    4: [  
        {"name": "Kucinguiaeo",   "element": Element.LIGHT, "role": ROLE_ATTACKER,
         "hp": 350, "attack": 82, "defense": 22,
         "image": "assets/characters/kucinguiaeo.png",
         "basic": {"name": "Thunder Paw",   "power": 0},
         "skill": {"name": "Lightning Claw","power": 60, "type": "attack", "cooldown": 3,
                   "desc": "Cakar listrik menyambar"}},
        {"name": "Serigalasumatra","element": Element.WIND,     "role": ROLE_HEALER,
         "hp": 330, "attack": 45, "defense": 32,
         "image": "assets/characters/serigalasumatra.png",
         "basic": {"name": "Wind Howl",     "power": 0},
         "skill": {"name": "Gale Restore",  "power": 85, "type": "heal",   "cooldown": 3,
                   "desc": "Angin penyembuh dari sumatra"}},
        {"name": "Mengerikan",    "element": Element.DARK,    "role": ROLE_TANKER,
         "hp": 510, "attack": 50, "defense": 70,
         "image": "assets/characters/mengerikan.png",
         "basic": {"name": "Spine Bash",    "power": 0},
         "skill": {"name": "Horror Guard",  "power": 52, "type": "attack", "cooldown": 3,
                   "desc": "Pertahanan mengerikan yang memukul balik"}},
    ],
    5: [  
        {"name": "mengerikan final boss",      "element": Element.DARK, "role": ROLE_TANKER,
         "hp": 10, "attack": 80, "defense": 99999,
         "image": "assets/characters/doraemon.png",
         "basic": {"name": "Future Shock",  "power": 10},
         "skill": {"name": "unidentified", "power": 45, "type": "attack", "cooldown": 3,
                   "desc": "unidentified"}},
    ],
}
